import { NgModule } from '@angular/core';
import {MatButtonModule, MatCheckboxModule,
  MatInputModule, MatIconModule,
    MatCardModule, MatGridListModule,
     MatSnackBarModule,
      MatDialogModule,
      MatMenuModule,
      MatRadioModule, MatTooltipModule, MatListModule, MatExpansionModule,
       MatBottomSheetModule, MatTabsModule, MatToolbarModule} from '@angular/material';
import { ReplacePipe } from './replace.pipe';
import { OrderByPipe } from './order.pipe';

@NgModule({
  declarations: [ReplacePipe, OrderByPipe],
  imports: [
    MatExpansionModule,
    MatTabsModule,
            MatButtonModule,
            MatInputModule,
            MatBottomSheetModule,
            MatIconModule,
            MatCardModule,
            MatGridListModule,
            MatSnackBarModule,
            MatDialogModule,
            MatRadioModule,
            MatTooltipModule,
            MatListModule,
            MatMenuModule,
            MatToolbarModule,
            MatCheckboxModule],
  exports: [ReplacePipe, OrderByPipe,
    MatExpansionModule,
    MatBottomSheetModule,
    MatTabsModule,
            MatButtonModule,
            MatInputModule,
            MatCardModule,
            MatIconModule,
            MatGridListModule,
            MatSnackBarModule,
            MatTooltipModule,
            MatDialogModule,
            MatRadioModule,
            MatListModule,
            MatMenuModule,
            MatToolbarModule,
            MatCheckboxModule],
})
export class MaterialComponentsRepositoryModule { }
